# Generated by Django 4.2.16 on 2026-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0018_poll_pollresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 View Analytics Dashboard',
                'verbose_name_plural': '📊 View Analytics Dashboard',
                'managed': False,
            },
        ),
    ]
