# Generated by Django 6.0.3 on 2026-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0019_analyticslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='alert_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='alert_48h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
