# Generated by Django 6.0.1 on 2026-03-19 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0020_notice_alert_24h_sent_notice_alert_48h_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., S3 MCA, S8 IMCA', max_length=50, unique=True)),
                ('department', models.CharField(choices=[('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA'), ('IMCA', 'IMCA')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Communities',
            },
        ),
        migrations.AlterField(
            model_name='notice',
            name='target_department',
            field=models.CharField(choices=[('All', 'All Departments'), ('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA'), ('IMCA', 'IMCA')], default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='target_department',
            field=models.CharField(choices=[('All', 'All Departments'), ('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA'), ('IMCA', 'IMCA')], default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('MCA', 'MCA'), ('BTech', 'BTech'), ('MBA', 'MBA'), ('IMCA', 'IMCA')], default='MCA', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_community',
            field=models.ForeignKey(blank=True, help_text='Leave blank to target the whole department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.community'),
        ),
        migrations.AddField(
            model_name='poll',
            name='target_community',
            field=models.ForeignKey(blank=True, help_text='Leave blank to target the whole department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.community'),
        ),
        migrations.AddField(
            model_name='profile',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notices.community'),
        ),
    ]
